### ISSUE TITLE
MassTransit v3 Implementation

### ISSUE THREAD

**Issue by Blundell89** [CaptiveAire/MassTransit.Persistence.MongoDb#6]
Hey @Jaben,

We've been working on the MassTransit v3 implementation but we decided to create this on our own repository due to the significant changes to the MassTransit API. We were wondering whether you could make us an owner on the same NuGet package feed (https://www.nuget.org/packages/MassTransit.Persistence.MongoDb/) so we could release v3 MongoDb persistence under the name identifier? that would allow people to seamlessly update to v3 of MassTransit and also allow you to continue to support v2 if required. Our Username is: LiberisDevTeam.

Thanks

Lee & Kev

**Comment by Jaben** [comment]
Absolutely
